/**
 * 拼接预设模板
 * mode: 'horizontal' | 'vertical' | 'grid' | 'custom'
 * slots: 模板格子数量
 * cols/rows: 网格列/行
 * layout: 自定义布局（grid-template-areas 风格，数字为 slot 索引）
 */
export const PRESETS = [
  {
    id: 'h2',
    name: '双图横排',
    mode: 'horizontal',
    slots: 2,
    cols: 2,
    rows: 1,
    desc: '左右各一张',
  },
  {
    id: 'v2',
    name: '双图竖排',
    mode: 'vertical',
    slots: 2,
    cols: 1,
    rows: 2,
    desc: '上下各一张',
  },
  {
    id: 'h3',
    name: '三图横排',
    mode: 'horizontal',
    slots: 3,
    cols: 3,
    rows: 1,
    desc: '横向连续展示',
  },
  {
    id: 'v3',
    name: '三图竖排',
    mode: 'vertical',
    slots: 3,
    cols: 1,
    rows: 3,
    desc: '纵向长图展示',
  },
  {
    id: 'grid3',
    name: '三宫格',
    mode: 'grid',
    slots: 3,
    cols: 3,
    rows: 1,
    desc: '一行三张',
  },
  {
    id: 'grid4',
    name: '2×2 宫格',
    mode: 'grid',
    slots: 4,
    cols: 2,
    rows: 2,
    desc: '四宫格',
  },
  {
    id: 'grid5',
    name: '五宫格',
    mode: 'grid',
    slots: 5,
    cols: 3,
    rows: 2,
    desc: '社媒多图',
  },
  {
    id: 'grid6',
    name: '2×3 宫格',
    mode: 'grid',
    slots: 6,
    cols: 2,
    rows: 3,
    desc: '六宫格',
  },
  {
    id: 'grid8',
    name: '四列八图',
    mode: 'grid',
    slots: 8,
    cols: 4,
    rows: 2,
    desc: '横向相册墙',
  },
  {
    id: 'grid9',
    name: '3×3 九宫格',
    mode: 'grid',
    slots: 9,
    cols: 3,
    rows: 3,
    desc: '朋友圈/Instagram 风格',
  },
  {
    id: 'left1right2',
    name: '1大2小',
    mode: 'custom',
    slots: 3,
    cols: 2,
    rows: 2,
    // layout: 第一张占左侧满高，右侧上下两张
    layout: [
      [0, 1],
      [0, 2],
    ],
    desc: '左大右二小',
  },
  {
    id: 'right1left2',
    name: '2小1大',
    mode: 'custom',
    slots: 3,
    cols: 2,
    rows: 2,
    layout: [
      [0, 2],
      [1, 2],
    ],
    desc: '左二右大',
  },
  {
    id: 'top1bottom2',
    name: '上大下二',
    mode: 'custom',
    slots: 3,
    cols: 2,
    rows: 2,
    layout: [
      [0, 0],
      [1, 2],
    ],
    desc: '封面图在上',
  },
  {
    id: 'top2bottom1',
    name: '上二下大',
    mode: 'custom',
    slots: 3,
    cols: 2,
    rows: 2,
    layout: [
      [0, 1],
      [2, 2],
    ],
    desc: '总结图在下',
  },
  {
    id: 'left1right3',
    name: '1大3小',
    mode: 'custom',
    slots: 4,
    cols: 2,
    rows: 3,
    layout: [
      [0, 1],
      [0, 2],
      [0, 3],
    ],
    desc: '左侧主图',
  },
  {
    id: 'top1bottom3',
    name: '上大下三',
    mode: 'custom',
    slots: 4,
    cols: 3,
    rows: 2,
    layout: [
      [0, 0, 0],
      [1, 2, 3],
    ],
    desc: '横版封面拼图',
  },
  {
    id: 'hero4',
    name: '主图+四辅',
    mode: 'custom',
    slots: 5,
    cols: 4,
    rows: 2,
    layout: [
      [0, 0, 1, 2],
      [0, 0, 3, 4],
    ],
    desc: '商品/作品集',
  },
  {
    id: 'magazine5',
    name: '杂志五图',
    mode: 'custom',
    slots: 5,
    cols: 3,
    rows: 3,
    layout: [
      [0, 0, 1],
      [0, 0, 2],
      [3, 4, 2],
    ],
    desc: '主次分明',
  },
  {
    id: 'banner6',
    name: '横幅六图',
    mode: 'custom',
    slots: 6,
    cols: 4,
    rows: 3,
    layout: [
      [0, 0, 1, 2],
      [0, 0, 3, 3],
      [4, 4, 5, 5],
    ],
    desc: '海报横幅感',
  },
  {
    id: 'longscroll',
    name: '长截图',
    mode: 'vertical',
    slots: 0, // 不限数量
    cols: 1,
    rows: 0,
    gap: 0,
    desc: '纵向无间距拼接',
  },
];
